
export const LOGIN = "LOGIN"
export const REGISTER = "REGISTER"
export const ALL_TWEETS = "ALL_TWEETS"
export const FRIEND_LIST = 'FRIEND_LIST'
export const GET_MOD_EVENTS='GET_MOD_EVENTS'
export const ADD_NEW_EVENT="ADD_NEW_EVENT"
export const ADD_NEW_TWEET="ADD_NEW_TWEET"
export const GET_MOD_FRIENDS="GET_MOD_FRIENDS"
export const GET_ALL_MOD="GET_ALL_MOD"
export const GET_MY_MOD="GET_MY_MOD"
export const GET_CURRENT_USER="GET_CURRENT_USER"
export const EDIT_CURRENT_USER="EDIT_CURRENT_USER"